### ISSUE TITLE
How to sample at a period of 1 millisecond

### ISSUE THREAD

**Issue by steveyeh9872** [VernierST/godirect-js#1008]
setting minMeasurementPeriod  = 1 and call gdx.start(1) would not work to sample every 1 millisecond.

**Comment by steveyeh9872** [comment]
want to sample data at frequency 1000hz

**Comment by sswartley** [comment]
Hello,

Some sensors are not able to sample that fast. It might also depend on the hardware you are using to act as the host. Another issue to be aware of is the length of time for fast sampling. Sampling fast for too long may end up in failures. That being said, a short duration test with a GDX-FOR was able to collect at 1000Hz most of the time (but not all of the time).

What Go Direct device are you using for testing? What is the maximum sample rate that you have been able to achieve?

All the best,

Sam

**Comment by steveyeh9872** [comment]
Hi Sam, 

My device is a Go Direct Force Plate, and I want to measure Force (N) in frequency 1000Hz. When I use gdx.start(period), I found the minimum measurement period is set to 10, so I was able to collect at most 100Hz.

**Comment by steveyeh9872** [comment]
In the GUI of the Go Direct Force Plate, I was able to collect at 1000Hz, and export (1000 data points in 1 sec). But in javascript, I failed to get 1000 data points in 1sec, even using gdx.start(1), think it is because the minMeasurementPeriod is fixed at 10.

**Comment by steveyeh9872** [comment]
@sswartley

**Comment by sswartley** [comment]
Sorry, we had a long holiday weekend, but now that we are back I will work to get you some more information for getting a faster data collection rate. What device are you running your code on? Are you connecting via USB or Bluetooth?

Thanks,

Sam

**Comment by steveyeh9872** [comment]
My device is a LG laptop (Windows 11), code written in Angular 10, and connect via Bluetooth.

**Comment by stocktonkincade** [comment]
@steveyeh9872, you are correct. The minMeasurementPeriod is fixed at 10 ms. I don't recall why that limit was initially set, but I have a local version of the library that allows me to collect at 1000 Hz. We will take a closer look and see if we can make a change that will allow periods of 1 ms, ASAP.

**Comment by steveyeh9872** [comment]
looking forward to your reply🥰

**Comment by stocktonkincade** [comment]
This library is not intended to do everything and so there are no protections against missing or corrupt measurements. As such we set the limit at 100 Hz in order to avoid potential bad behaviors. We also want to be careful to not promise more than the library is designed to handle. @steveyeh9872, I have reached out to you directly to continue the conversation about alternatives.

**Comment by steveyeh9872** [comment]
Hi Ian, I have replied your email. In short, I still failed to get 1000HZ even I have set minMeasurementPeriod to 1.
